baseurl = "/"
languageCode = "en-us"
title = "ManyClasses"
theme = "hugo-lithium"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[blackfriday]
    fractions = false

[[menu.main]]
    name = "About"
    url = "/"
[[menu.main]]
    name = "Projects"
    url = "/projects"
[[menu.main]]
    name = "Updates"
    url = "/updates"


[params]
    description = "ManyClasses is a research consortium investigating the generalizability of interventions in the classroom."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"
    
    [[params.social]]
      name = "Twitter"
      faicon = "fa-twitter"
      URL = "https://twitter.com/manyclasses"

